GET https://bad-api-assignment.reaktor.com/products/shirts
x-force-error-mode: all

####

GET https://bad-api-assignment.reaktor.com/products/jackets

###

GET https://bad-api-assignment.reaktor.com/products/accessories